### ISSUE TITLE
[Suggestion] Make it so that "Settings" don't redirect to the LethalSettings screen directly

### ISSUE THREAD

**Issue by Fl4sHNoX** [willis81808/LethalSettings#5]
I would prefer to have the LethalSettings only show up when I click on its dedicated button from the vanilla settings screen and not have it open up right away as I click on "Settings" from the pause screen, so that I have to click on "Back" to edit my other audio settings.

**Comment by willis81808** [comment]
This behavior is the same as the existing control bindings menu when you close and reopen settings using “escape” without pressing the back button first.

**Comment by ZigzagAwaka** [comment]
Fixed in the latest update
