### ISSUE TITLE
[Bug] LethalSettings opens itself when entering the Settings menu

### ISSUE THREAD

**Issue by JohnMetroid** [willis81808/LethalSettings#6]
Not sure what else to add.  I just installed LethalSettings because it's a dependency for Mirage now.  Upon first entry into the Settings menu each time the Lethal Company client is loaded, clicking the Settings menu will automatically load straight into the LethalSettings submenu instead of just the settings menu.

Cheers.

**Comment by ZigzagAwaka** [comment]
Hey! This was fixed in the latest update

**Comment by JohnMetroid** [comment]
Indeed it was.  Closing this one out
